### ISSUE TITLE
How to use a method from a custom class as the func in ObservationTermCfg

### ISSUE THREAD

**Issue by 67815674** [isaac-sim/IsaacLabExtensionTemplate#38]
When I try to create a class to manage the observation functions by myself, I encounter an error.
`Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/hydra.py", line 85, in hydra_main
    env_cfg.from_dict(hydra_env_cfg["env"])
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/configclass.py", line 140, in _update_class_from_dict
    update_class_from_dict(obj, data, _ns="")
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/dict.py", line 87, in update_class_from_dict
    update_class_from_dict(obj_mem, value, _ns=key_ns)
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/dict.py", line 87, in update_class_from_dict
    update_class_from_dict(obj_mem, value, _ns=key_ns)
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/dict.py", line 110, in update_class_from_dict
    value = string_to_callable(value)
  File "/home/robot/code/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/string.py", line 158, in string_to_callable
    callable_object = getattr(mod, attr_name)
AttributeError: module 'robot_lab.tasks.locomotion.walker.mdp.observations' has no attribute 'get_gait_phase'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

**Comment by 67815674** [comment]
These are part of the code for my custom class```
class ObsTermAppends:
    """
        观测参数拓展
    """
    def __init__(self):
        self.cycle_time = 0.64
        self.target_joint_pos_scale = 0.2
        self.num_envs = 4096
        self.N = 10

    def get_gait_phase(self, env : ManagerBasedRLEnv, asset_cfg: SceneEntityCfg = SceneEntityCfg("robot")):
        # return float mask 1 is stance, 0 is swing
        asset: Articulation = env.scene[asset_cfg.name]
        self.ref_dof_pos = torch.zeros_like(asset.data.joint_pos[:, asset_cfg.joint_ids])
        self.phase = env.episode_length_buf * env.step_dt / self.cycle_time
        self.stance_mask = torch.zeros((env.num_envs, 2))
        self.compute_ref_state
        sin_pos = torch.sin(2 * torch.pi * self.phase)
        # Add double support phase
        self.stance_mask.zero_()
        # left foot stance
        self.stance_mask[:, 0] = sin_pos >= 0
        # right foot stance
        self.stance_mask[:, 1] = sin_pos < 0
        # Double support phase
        self.stance_mask[torch.abs(sin_pos) < 0.1] = 1
        return self.stance_mask

```
and，I am using these functions like this：
```
class ObservationsCfg:
    """Observation specifications for the MDP."""
    obsAppends = ObsTermAppends()

    get_gait_phase = ObsTerm(
        func=obsAppends.get_gait_phase,
    )
    diff_ref_pos = ObsTerm(
        func=obsAppends.diff_ref_pos,
    )
    # observation terms (order preserved)
    base_pos_z = ObsTerm(
        func=obsAppends.base_lin_vel,
        noise=Unoise(n_min=-0.1, n_max=0.1),
    )
    base_lin_vel = ObsTerm(
        func=obsAppends.base_lin_vel,
        noise=Unoise(n_min=-0.1, n_max=0.1),
    )
    base_ang_vel = ObsTerm(
        func=obsAppends.base_ang_vel,
        noise=Unoise(n_min=-0.2, n_max=0.2),
    )
```

**Comment by 67815674** [comment]
and，I am using these functions like this：```
class ObservationsCfg:
    """Observation specifications for the MDP."""
    obsAppends = ObsTermAppends()

    get_gait_phase = ObsTerm(
        func=obsAppends.get_gait_phase,
    )
    diff_ref_pos = ObsTerm(
        func=obsAppends.diff_ref_pos,
    )
    # observation terms (order preserved)
    base_pos_z = ObsTerm(
        func=obsAppends.base_lin_vel,
        noise=Unoise(n_min=-0.1, n_max=0.1),
    )
    base_lin_vel = ObsTerm(
        func=obsAppends.base_lin_vel,
        noise=Unoise(n_min=-0.1, n_max=0.1),
    )
    base_ang_vel = ObsTerm(
        func=obsAppends.base_ang_vel,
        noise=Unoise(n_min=-0.2, n_max=0.2),
    )
```

**Comment by fan-ziqi** [comment]
Hi, you can write like this

Add a new obs func in `robot_lab.tasks.locomotion.velocity.mdp`
```python
def phase(env: ManagerBasedRLEnv) -> torch.Tensor:
    # Compute phase here
    phase_tensor = xxx
    return phase_tensor
```
Then import and use it 
```python
import robot_lab.tasks.locomotion.velocity.mdp as mdp
from robot_lab.tasks.locomotion.velocity.velocity_env_cfg import ObservationsCfg

@configclass
class XXXObservationsCfg(ObservationsCfg):
    @configclass
    class PolicyCfg(ObservationsCfg.PolicyCfg):
        phase = ObsTerm(func=mdp.phase, scale=1.0)

        def __post_init__(self):
            super().__post_init__()

    policy: PolicyCfg = PolicyCfg()
```

**Comment by MissWu-615** [comment]
I have a similar question, I defined my own ObservationsCfg, ActionCfg, EventCfg, CommandsCfg, beacuse I didn't want to be covered if I used the configuration form robot_lab.tasks.locomotion.velocity.velocity_env_cfg, but when I trained, there is an  error:Could not find git repository in /home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/__init__.py. Skipping.
Storing git diff for 'IsaacLab' in: /home/wu/Downloads/IsaacLab/logs/rsl_rl/tinker_flat/2025-03-26_17-48-44/git/IsaacLab.diff
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/wu/Downloads/IsaacLab/scripts/reinforcement_learning/rsl_rl/train.py", line 153, in <module> main()
  File "/home/wu/Downloads/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/utils/hydra.py", line 104, in wrapper hydra_main()
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main  _run_hydra(
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
  _run_app(
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/wu/Downloads/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/utils/hydra.py", line 101, in hydra_main
    func(env_cfg, agent_cfg, *args, **kwargs)
  File "/home/wu/Downloads/IsaacLab/scripts/reinforcement_learning/rsl_rl/train.py", line 145, in main
    runner.learn(num_learning_iterations=agent_cfg.max_iterations, init_at_random_ep_len=True)
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/runners/on_policy_runner.py", line 113, in learn
    actions = self.alg.act(obs, critic_obs)
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/algorithms/ppo.py", line 75, in act
    self.transition.actions = self.actor_critic.act(obs).detach()
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/modules/actor_critic.py", line 105, in act
    self.update_distribution(observations)
  File "/home/wu/miniconda3/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/modules/actor_critic.py", line 102, in update_distribution
    self.distribution = Normal(mean, mean * 0.0 + self.std)
  File "/home/wu/Downloads/isaacsim/exts/omni.isaac.ml_archive/pip_prebundle/torch/distributions/normal.py", line 59, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/wu/Downloads/isaacsim/exts/omni.isaac.ml_archive/pip_prebundle/torch/distributions/distribution.py", line 71, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (500, 10)) of distribution Normal(loc: torch.Size([500, 10]), scale: torch.Size([500, 10])) to satisfy the constraint Real(), but found invalid values:
tensor([[ 0.0005, -0.1112,  0.1013,  ...,  0.0517, -0.0309, -0.1245],
        [-0.0250, -0.1002,  0.1011,  ...,  0.0629, -0.0326, -0.1150],
        [ 0.0355, -0.0955,  0.0909,  ...,  0.0599, -0.0542, -0.1233],
        ...,
        [-0.0105, -0.0870,  0.1079,  ...,  0.0691,  0.0345, -0.1311],
        [ 0.0274, -0.0662,  0.0939,  ...,  0.0541, -0.0115, -0.0833],
        [ 0.0296, -0.0955,  0.0901,  ...,  0.0424, -0.0467, -0.1041]],
       device='cuda:0')                                                                                                                                                                                                Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
