### ISSUE TITLE
gymnasium.error.NameNotFound: Environment `Isaac-SmplHumanoid` doesn't exist.

### ISSUE THREAD

**Issue by BRoln7** [isaac-sim/IsaacLabExtensionTemplate#41]

**Comment by BRoln7** [comment]
![1](https://github.com/user-attachments/assets/3cbf7ad9-7781-4ef9-8408-b7d77082d1c3)
I registered a manager-based environment named "Isaac-SmplHumanoid", as shown in this figure. But there were something wrong:
`Traceback (most recent call last):
  File "/home/social-navigation/miniconda3/envs/isaaclab/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/social-navigation/miniconda3/envs/isaaclab/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/social-navigation/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/home/social-navigation/socnav_sim/scripts/sb3/pacer-isaac/inference.py", line 96, in <module>
    main()
  File "/home/social-navigation/socnav_sim/scripts/sb3/pacer-isaac/inference.py", line 47, in main
    env_cfg = parse_env_cfg(
  File "/home/social-navigation/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/parse_cfg.py", line 136, in parse_env_cfg
    cfg = load_cfg_from_registry(task_name, "env_cfg_entry_point")
  File "/home/social-navigation/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/parse_cfg.py", line 55, in load_cfg_from_registry
    cfg_entry_point = gym.spec(task_name).kwargs.get(entry_point_key)
  File "/home/social-navigation/miniconda3/envs/isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 1029, in spec
    _check_version_exists(ns, name, version)
  File "/home/social-navigation/miniconda3/envs/isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 393, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/social-navigation/miniconda3/envs/isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 370, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `Isaac-SmplHumanoid` doesn't exist. Did you mean: `Isaac-Humanoid`?`
What's the problem?

**Comment by dhruvil122** [comment]
Can you tell me how did you solve this? Facing the same problem.

**Comment by BRoln7** [comment]
In the main file (e.g., train.py), add `import your_fancy_extension_name.task`
